import { Action } from '../Action';
import { RegisterDispatcher } from '../RegisterDispatcher';
import { AutogeneratedActionType } from './AutogeneratedActionType.decorator';


export function ActionClass() {
	return <Args extends any[], T>(target: new(...args: Args) => T): new(...args: Args) => T & Action & RegisterDispatcher => {
		target = AutogeneratedActionType()(target);
		return target as any;
	}
}
